### ISSUE TITLE
Use mongoDb

### ISSUE THREAD

**Issue by manuelc27** [COMP313Team03/EasyCook#1]
Find a host for a mongodb DB and develop an application to test the connection, insert, and retrieve data.

First attend with MongoLab and a Java application.

**Comment by manuelc27** [comment]
Find a host for a mongodb DB and develop an application to test the connection, insert, and retrieve data.

First attend with MongoLab and a Java application.

**Comment by manuelc27** [comment]
Connection string for mongoDB console on MongoLab

`mongo ds055525.mongolab.com:55525/easycook -u admin -p 123456`

**Comment by manuelc27** [comment]
Connection string for java app

`mongodb://<dbuser>:<dbpassword>@ds055525.mongolab.com:55525/easycook`

**Comment by dpandya76** [comment]
Tested the code for connection to mongodb and inserted sample data..
