### ISSUE TITLE
Create a presentation work flow for the final release(Acceptance Test)

### ISSUE THREAD

**Issue by safranc** [COMP313Team03/EasyCook#23]
The document should contain the following
        1.Entire workflow of the application with videos.
        2.Pass all core Acceptance Tests
        3.Explain "how to use and run the application".

**Comment by SruthiKuppa** [comment]
TESTCASES DOCUMENT INCLUDED.

https://drive.google.com/drive/folders/0BwMkR6nAwlyEYm1NNDVVdkdQTmc

APPLICATION SUCCESSFULLY EXECUTES
